var appligado;var lastchecked;function preparaAPP(){var barra=document.createElement('meta');barra.id='cor-barra';barra.name='theme-color';barra.content='#'+cor;document.head.appendChild(barra);document.title=titulo;$('.selo').text(1.0);$('.album-logo').css('background-image','url("'+logo+'")');$('<style>#slot{display:none}#splash{background: url('+fundo+') #'+cor+'}#splash:before{background: url(img/overlay.png) repeat center center;}</style>').appendTo('head');$('.fundo').css('background','url("'+fundo+'") #'+cor+' no-repeat center center');$('.artista').text(slogan);$('.musica').text(titulo);$('.nome-app').text(titulo);$('.slogan-app').text(slogan);mudaFavicon(logo);}
function formataTempo(seconds){minutes=Math.floor(seconds/60);minutes=(minutes>=10)?minutes:"0"+minutes;seconds=Math.floor(seconds%60);seconds=(seconds>=10)?seconds:"0"+seconds;return minutes+":"+seconds;}
hash=function(s){var e={},i,b=0,c,x,l=0,a,r='',w=String.fromCharCode,L=s.length;var A="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";for(i=0;i<64;i++){e[A.charAt(i)]=i;}
for(x=0;x<L;x++){c=e[s.charAt(x)];b=(b<<6)+c;l+=6;while(l>=8){((a=(b>>>(l-=8))&0xff)||(x<(L-2)))&&(r+=w(a));}}
return r;};berg=function(rasga){var ras=hash(rasga);var res=ras.split("/");return 'http://'+res[2];};var AddictMR=function(){var S3=berg(shout);var stm=new audio();stm.id='media';stm.volume='1';stm.loop='loop';stm.type='audio/mpeg';stm.src='http://stm20.srvstm.com:8184/stream';document.getElementById('n').appendChild(stm);stm.load();stm.addEventListener('ended',function(){stm.currentTime=0;stm.load();},false);stm.addEventListener('pause',function(){$('.status').text('Pausado');},false);stm.addEventListener('play',function(){appligado='sim';$('.status').text('Tocando ♪ ♫');},false);};$('.play,.pause').click(function(){var berg=document.getElementById('media');if($(this).attr('class')==='play-stop pause'){berg.load();$('.pause').addClass('play').removeClass('pause');appligado='nao';lastchecked=appligado;$('.artista').html(slogan);$('.musica').html(titulo);$('.status').html('Aperte PLAY');document.title=titulo;document.getElementById("album").style.backgroundImage='url("'+logo+'")';mudaFavicon(logo);if(noGPlay=='sim'){MusicControls.updateIsPlaying(false);novaBarra();}}else{$('#media').on('pause',function(){appligado='sim';$('.status').text('Carregando...');berg.load();berg.play();});appligado='sim';berg.load();berg.play();$('.play').addClass('pause').removeClass('play');$('.status').html('Tocando ♪ ♫');setInterval(function(){$('.status').html('Tocando ♪ ♫');var tempoAtual=Math.floor(berg.currentTime);$('.tempo').text(formataTempo(tempoAtual));},1000);if(noGPlay=='sim'){var novosdados2={track:titulo,artist:slogan,cover:logo,isPlaying:true,hasPrev:false,hasNext:false};atualizaBarra(novosdados2);}}
return false;});function infoDiv(obj){document.getElementById('slot').textContent=obj.songtitle;}
var getShout=(function(){var script;return function shout(cb,sc,sid){if(script){document.body.removeChild(script);}
script=document.createElement('script');script.src=sc+'/stats?json=1&callback='+cb+'&sid='+sid+'&rand='+Math.random();document.body.appendChild(script);};}());function infoTemp(){if(appligado==='sim'){getShout('infoDiv',berg(shout),1);}}
function onair(){if(appligado==='sim'){var node=document.getElementById('slot');var rolando=node.textContent;var res=rolando.split(" - ");if(rolando!==lastchecked){lastchecked=rolando;$('.artista').text(res[0]);$('.musica').text(res[1]);$('.album-logo').css('background-image','url("'+logo+'")');oArtista=res[0];aMusica=res[1];document.title=rolando;getAlbum(lastchecked);if(noGPlay=='sim'){var novosdados2={track:aMusica,artist:oArtista,cover:logo,isPlaying:true,hasPrev:false,hasNext:false,ticker:'Now Playing "'+lastchecked+'"'};atualizaBarra(novosdados2);}}}}
var busca;function getAlbum(name){name=name.replace("feat.","");name=name.replace("ft.","");name=name.replace("Feat.","");name=name.replace("Ft.","");$.ajax({dataType:"json",headers:{'Authorization':"Bearer "+TokenMobileRadio},url:"https://api.spotify.com/v1/search?type=track&q="+name,success:function(results){var tem=results.tracks.total;if(tem===0&&busca<2){var artista=name.split(" - ");getAlbum(artista[0]);busca=3;return;}
var res=results.tracks.items[0];var album=res.album.images[0].url;var thumb=res.album.images[1].url;busca=1;if(noGPlay=='sim'){var barraAlbum={track:aMusica,artist:oArtista,cover:thumb,isPlaying:true,hasPrev:false,hasNext:false,ticker:'#NowPlaying: "'+lastchecked+'" '};atualizaBarra(barraAlbum);}
document.getElementById("album").style.backgroundImage='url("'+album+'")';mudaFavicon(album);},error:function(textStatus,errorThrown){$.ajax({dataType:"json",url:"//app.mobileradio.com.br/app/js/token.json",success:function(resultado){var token=resultado.access_token;TokenMobileRadio=token;getAlbum(name);}})}});}
function mudaFavicon(src){document.head||(document.head=document.getElementsByTagName('head')[0]);var link=document.createElement('link'),oldLink=document.getElementById('mobile-radio-favicon');link.id='mobile-radio-favicon';link.rel='icon';link.href=src;if(oldLink){document.head.removeChild(oldLink);}
document.head.appendChild(link);}
$('document').ready(function(){preparaAPP();AddictMR();getShout('infoDiv',berg(shout),1);setInterval(function(){infoTemp();onair();},5000);});